import type { Metadata } from 'next'
import './globals.css'
import { Roboto } from 'next/font/google'
import { Playfair_Display } from 'next/font/google'
import TopHeader from '@/components/layout/Header/TopHeader'
import BottomHeader from '@/components/layout/Header/BottomHeader'
import Footer from '@/components/layout/Footer/Footer'
import FooterCart from '@/components/layout/Footer-cart/FooterCart'
import { CartProvider } from '@/app/hooks/cartContext'

const roboto = Roboto({
  subsets: ['latin', 'cyrillic'],
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-roboto',
})

const playfairDisplay = Playfair_Display({
  subsets: ['latin', 'cyrillic'],
  weight: '400',
  style: 'normal',
  display: 'swap',
  variable: '--font-playfair-display',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body
        className={`${roboto.className} ${playfairDisplay.variable} antialiased flex flex-col min-h-screen`}
      >
        <CartProvider>
          <TopHeader />
          <BottomHeader />
          <main className="flex-1">
            {children}
          </main>
          <footer className="shrink-0">
            <FooterCart />
            <Footer />
          </footer>
        </CartProvider>
      </body>
    </html>
  )
}
