import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header/Header";

import { Roboto } from "next/font/google";
import { Playfair_Display } from "next/font/google";
import Footer from "@/components/layout/Footer/Footer";

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-roboto",
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin", "cyrillic"],
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={` ${roboto.className} ${playfairDisplay.variable} antialiased `}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
